### ISSUE TITLE
busy-wait loop during pop

### ISSUE THREAD

**Issue by usergoodvery** [grivet/mpsc-queue#1]
Hi
I was reviewing your code and noticed you're doing a busy-wait loop on the MPSC_QUEUE_RETRY condition. According to Vyukov the algo is lock based with respect to the consumer. Is that your way of signalling that back to the user?
`do {
        result = mpsc_queue_poll(queue, &node);
        if (result == MPSC_QUEUE_EMPTY) {
            return NULL;
        }
    } while (result == MPSC_QUEUE_RETRY);`

**Comment by grivet** [comment]
Indeed, the enum mpsc_queue_poll_result is a way to differentiate the state of the queue for the consumer. Without locks, the user will probably have to use exponential backoff. Whether the queue is empty or inconsistent is thus important to know: if empty the user can backoff, otherwise it can choose to retry shortly.

The function mpsc_queue_pop() is a helper for the common case, where the user will actually want to just loop until the queue is consistent. This is assuming all threads are cooperative and we know that no producer was preempted while inserting in the queue.

The queue is obstruction-free only due to having to work with this assumption about other threads. Either they are cooperative and mpsc_queue_pop() is fine, or the system must have another way to ensure forward-progress from the producers to avoid blocking the consumer. Maybe enabling a critical section before insertion, or other things specific to the OS running the code.

There is a small article on this subject here: https://u256.net/posts/mpsc-queue.html

**Comment by usergoodvery** [comment]
Thanks for the reply and also the ref to the article--good write up. I think the semantics you introduced are quite smart and an improvement on the original prototype.
 
You also created a simple locking mechanism (assuming primarily for the consumer), What do you see the utility of that? Or is that something specific to your own usecase (outside the scope of the original algorithm)?

**Comment by grivet** [comment]
The original idea for the dumb lock added to the queue was to have a type that could be used to annotate functions for thread-safety analysis (when using clang). Having a very dumb lock is easy, but then it's a bad lock anyway. I dont want to add a dependency on pthread, so I can't add those annotations relying on pthread's type.

Moreover, choosing the locking type means taking space in the queue struct and making this choice instead of the user -- wasting bytes if it's not the proper one.

So I decided to remove the lock altogether. There is no clean way to annotate for safety analysis. Trying to improve there invites scope creep. The API doc will have to be sufficient to guard against misuse.

**Comment by usergoodvery** [comment]
Agreed this type of complexity should not be present at API level--it's user's responsibility to design for that.

**Comment by grivet** [comment]
Thanks for your questions, if that's alright with you I will close this issue. If you have further questions don't hesitate to re-open, create a new one or reach out by other means :) .
